#!/bin/sh -e

heading() {
  echo "==> $1 <=="
}

if test -z "$locale" -o -z "$charset"
	 then
	 	echo "locale/charset not set"
	 	exit
	 fi
	
export DEBIAN_FRONTEND=noninteractive


echo "LANG=$locale.$charset" > /etc/default/locale
echo "$locale.$charset $charset" > /etc/locale.gen

heading "Remove unnecessary locales"

# This little lot is the result of me knowing far more about find than I have *ever* wanted to.
find /usr/lib/locale -mindepth 1 -maxdepth 1 -type d -a \( \( -name "C.*" -o -name "$locale*" \) -prune -o -name \* -a -print \) | xargs -r rm -r
find /usr/share/locale -mindepth 1 -maxdepth 1 -type d -a \( \( -name "locale.alias" -o -name "$locale*" \) -prune -o -name \* -a -print \) | xargs -r rm -r
 if test -d /usr/share/i18n/locales
 	 then
		find /usr/share/i18n/locales -depth -mindepth 1 -maxdepth 1 \( -name "C" -o -name "POSIX" -o -name "$locale" -o -name en_GB -o -name en_US -o -name "i18n*" -o -name "iso*" -o -name "translit*" \) -prune -o -name \* -a -delete
	fi	

locale-gen

